name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - '*'

jobs:
  build_docs:
    name: Documentation
    runs-on: 'ubuntu-latest'
    timeout-minutes: 120
    defaults:
      run:
        shell: bash -l {0}
    env:
      DESC: "Documentation build"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Conda environment setup
        run: |
          conda config --set always_yes True
          conda install -c pyviz "pyctdev>=0.5"
          doit ecosystem_setup
          doit env_create
          doit env_capture
      - name: Build website
        run: |
          eval "$(conda shell.bash hook)"
          conda activate test-environment
          doit build_website
      - name: git status
        run: |
          git status
          git diff
      - name: Deploy site
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builtdocs
          cname: status.holoviz.org
          force_orphan: true
